SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `fun` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `fun`;

CREATE TABLE IF NOT EXISTS `brow` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `imagePath` varchar(200) NOT NULL,
  `width` varchar(50) NOT NULL,
  `height` varchar(50) NOT NULL,
  `createTime` varchar(100) NOT NULL,
  `pathID` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=530 ;

CREATE TABLE IF NOT EXISTS `hoax` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `author` varchar(50) DEFAULT NULL,
  `authorPic` varchar(200) DEFAULT NULL,
  `content` text,
  `support` int(11) DEFAULT NULL,
  `createTime` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3086 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
